let eventGuid = 0;
let todayStr = new Date();
export function createEventId() {
  return String(eventGuid++);
}

export const INITIAL_EVENTS = [
  {
    id: 1,
    image: "",
    start: "2024-03-14",
    end: "2024-08-26",
    compName: "업체명업체명업체명",
    description: "공고제목공고제목공고제목공고제목공고제목공고제목",
    jobType: "직무,직종직무,직종",
    noticeDedline: "~ 99/99",
    backgroundType: "경력 무관   ㅣ  학력 무관",
  },

  {
    id: 2,
    start: "2023-08-27",
    end: "2023-08-27",
    image: "/assets/images/recruitments/Rectangle 7 (1).png",
    compName: "SBS 미디어넷",
    description: "D콘텐츠사업팀 [Pick Up! 트렌드 스페셜] AD 모집",
    jobType: "방송/광고 운행",
    noticeDedline: "~ 99/99",
    backgroundType: "경력 무관   ㅣ  초대졸 부터",
  },
  {
    id: 3,
    start: todayStr.toISOString().replace(/T.*$/, ""),
    end: todayStr.toISOString().replace(/T.*$/, ""),
    image: "/assets/images/recruitments/Rectangle 13.png",
    compName: "서울경제TV",
    description: "제작팀 제작PD 모집",
    jobType: "방송/기술",
    noticeDedline: "~ 99/99",
    backgroundType: "5년 부터   ㅣ  학력 무관      ",
  },
  {
    id: 4,
    start: "2023-08-18",
    end: "2023-08-18",
    image: "/assets/images/recruitments/Rectangle 13 (1).png",
    compName: "미디어로그 ",
    description: "LG U+ 스포키앱 운영 모집(안양 평촌역) 4명 채용",
    jobType: "방송/방송사무",
    noticeDedline: "~ 99/99",
    backgroundType: "경력 무관   ㅣ  학력 무관",
  },
  {
    id: 5,
    start: "2023-08-10",
    end: "2023-08-10",
    image: "/assets/images/recruitments/Rectangle 8.png",
    compName: "메가스터디교육㈜",
    description: "컨텐츠제작팀 강의 라이브 송출 및 모니터링 (역삼)",
    jobType: "방송/송출/카메라",
    noticeDedline: "~ 99/99",
    backgroundType: "경력 무관   ㅣ  학력 무관 ",
  },
  {
    id: 6,
    start: "2023-08-11",
    end: "2023-08-11",
    image: "/assets/images/recruitments/Rectangle 7 (2).png",
    compName: "MBC                ",
    description: '예능국 "태어난김에 세계일주2" FD 모집',
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "경력 무관   ㅣ  고졸 부터",
  },
  {
    id: 7,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 7 (3).png",
    compName: "미디어로그 lasjdhalsdnlakjsdlasd.;kl",
    description: "프로덕션툴즈 중계기술팀 중계차 영상감독/현장오디오감독",
    jobType: "방송/오디오",
    noticeDedline: "~ 99/99",
    backgroundType: "경력 무관   ㅣ  고졸 부터",
  },
  {
    id: 8,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 13 (2).png",
    compName: "SPOTV",
    description:
      "프로덕션툴즈 기술관리팀 스튜디오/중계카메라(KBO,KBL) 모집(남녀무관)",
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "3년 부터   ㅣ  고졸 부터   ",
  },
  {
    id: 9,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 13 (2).png",
    compName: "SPOTV",
    description:
      "프로덕션툴즈 기술관리팀 스튜디오/중계카메라(KBO,KBL) 모집(남녀무관)",
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "3년 부터   ㅣ  고졸 부터   ",
  },
  {
    id: 10,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 13 (2).png",
    compName: "SPOTV",
    description:
      "프로덕션툴즈 기술관리팀 스튜디오/중계카메라(KBO,KBL) 모집(남녀무관)",
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "3년 부터   ㅣ  고졸 부터   ",
  },
  {
    id: 11,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 13 (2).png",
    compName: "SPOTV",
    description:
      "프로덕션툴즈 기술관리팀 스튜디오/중계카메라(KBO,KBL) 모집(남녀무관)",
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "3년 부터   ㅣ  고졸 부터   ",
  },
  {
    id: 12,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 13 (2).png",
    compName: "SPOTV",
    description:
      "프로덕션툴즈 기술관리팀 스튜디오/중계카메라(KBO,KBL) 모집(남녀무관)",
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "3년 부터   ㅣ  고졸 부터   ",
  },
  {
    id: 13,
    start: "2023-08-12",
    end: "2023-08-12",
    image: "/assets/images/recruitments/Rectangle 13 (2).png",
    compName: "SPOTV asdasdasdasd",
    description:
      "프로덕션툴즈 기술관리팀 스튜디오/중계카메라(KBO,KBL) 모집(남녀무관)",
    jobType: "방송/조연출",
    noticeDedline: "~ 99/99",
    backgroundType: "3년 부터   ㅣ  고졸 부터   ",
  },
];
